// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_events.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createActivityEvent = `-- name: CreateActivityEvent :exec
INSERT INTO activity_events (event_type, album_id, photo_id, share_link_id) VALUES (?, ?, ?, ?)
`

type CreateActivityEventParams struct {
	EventType   string        `json:"event_type"`
	AlbumID     sql.NullInt64 `json:"album_id"`
	PhotoID     sql.NullInt64 `json:"photo_id"`
	ShareLinkID sql.NullInt64 `json:"share_link_id"`
}

func (q *Queries) CreateActivityEvent(ctx context.Context, arg CreateActivityEventParams) error {
	_, err := q.db.ExecContext(ctx, createActivityEvent,
		arg.EventType,
		arg.AlbumID,
		arg.PhotoID,
		arg.ShareLinkID,
	)
	return err
}

const listRecentActivity = `-- name: ListRecentActivity :many
SELECT id, event_type, album_id, photo_id, share_link_id, created_at FROM activity_events ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListRecentActivityParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListRecentActivity(ctx context.Context, arg ListRecentActivityParams) ([]ActivityEvent, error) {
	rows, err := q.db.QueryContext(ctx, listRecentActivity, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityEvent{}
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AlbumID,
			&i.PhotoID,
			&i.ShareLinkID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
