// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type ActivityEvent struct {
	ID          int64         `json:"id"`
	EventType   string        `json:"event_type"`
	AlbumID     sql.NullInt64 `json:"album_id"`
	PhotoID     sql.NullInt64 `json:"photo_id"`
	ShareLinkID sql.NullInt64 `json:"share_link_id"`
	CreatedAt   sql.NullTime  `json:"created_at"`
}

type Album struct {
	ID           int64          `json:"id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	CoverPhotoID sql.NullInt64  `json:"cover_photo_id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type Photo struct {
	ID        int64        `json:"id"`
	AlbumID   int64        `json:"album_id"`
	Filename  string       `json:"filename"`
	Width     int64        `json:"width"`
	Height    int64        `json:"height"`
	SizeBytes int64        `json:"size_bytes"`
	Format    string       `json:"format"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type ProcessingQueue struct {
	ID               int64          `json:"id"`
	AlbumID          int64          `json:"album_id"`
	OriginalFilename string         `json:"original_filename"`
	TempFilepath     string         `json:"temp_filepath"`
	Status           string         `json:"status"`
	ErrorMessage     sql.NullString `json:"error_message"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type SchemaMigration struct {
	Version   int64        `json:"version"`
	AppliedAt sql.NullTime `json:"applied_at"`
}

type Session struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type ShareLink struct {
	ID         int64         `json:"id"`
	Token      string        `json:"token"`
	TargetType string        `json:"target_type"`
	TargetID   int64         `json:"target_id"`
	MaxViews   sql.NullInt64 `json:"max_views"`
	ExpiresAt  sql.NullTime  `json:"expires_at"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	RevokedAt  sql.NullTime  `json:"revoked_at"`
}

type ShareLinkView struct {
	ID          int64        `json:"id"`
	ShareLinkID int64        `json:"share_link_id"`
	ViewerHash  string       `json:"viewer_hash"`
	CreatedAt   sql.NullTime `json:"created_at"`
}
