// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package sqlc

import (
	"context"
)

const countPhotos = `-- name: CountPhotos :one
SELECT COUNT(*) FROM photos
`

func (q *Queries) CountPhotos(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPhotos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos (album_id, filename, width, height, size_bytes, format)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, album_id, filename, width, height, size_bytes, format, created_at
`

type CreatePhotoParams struct {
	AlbumID   int64  `json:"album_id"`
	Filename  string `json:"filename"`
	Width     int64  `json:"width"`
	Height    int64  `json:"height"`
	SizeBytes int64  `json:"size_bytes"`
	Format    string `json:"format"`
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRowContext(ctx, createPhoto,
		arg.AlbumID,
		arg.Filename,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.Format,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Filename,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Format,
		&i.CreatedAt,
	)
	return i, err
}

const deletePhoto = `-- name: DeletePhoto :exec
DELETE FROM photos WHERE id = ?
`

func (q *Queries) DeletePhoto(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePhoto, id)
	return err
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, album_id, filename, width, height, size_bytes, format, created_at FROM photos WHERE id = ?
`

func (q *Queries) GetPhoto(ctx context.Context, id int64) (Photo, error) {
	row := q.db.QueryRowContext(ctx, getPhoto, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Filename,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Format,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalStorageBytes = `-- name: GetTotalStorageBytes :one
SELECT COALESCE(SUM(size_bytes), 0) FROM photos
`

func (q *Queries) GetTotalStorageBytes(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalStorageBytes)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listPhotosByAlbum = `-- name: ListPhotosByAlbum :many
SELECT id, album_id, filename, width, height, size_bytes, format, created_at FROM photos WHERE album_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListPhotosByAlbumParams struct {
	AlbumID int64 `json:"album_id"`
	Limit   int64 `json:"limit"`
	Offset  int64 `json:"offset"`
}

func (q *Queries) ListPhotosByAlbum(ctx context.Context, arg ListPhotosByAlbumParams) ([]Photo, error) {
	rows, err := q.db.QueryContext(ctx, listPhotosByAlbum, arg.AlbumID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.Filename,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.Format,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
