// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countPhotos = `-- name: CountPhotos :one
SELECT COUNT(*) FROM photos
`

func (q *Queries) CountPhotos(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPhotos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos (album_id, filename, width, height, size_bytes, format)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, album_id, filename, width, height, size_bytes, format, created_at
`

type CreatePhotoParams struct {
	AlbumID   int64  `json:"album_id"`
	Filename  string `json:"filename"`
	Width     int64  `json:"width"`
	Height    int64  `json:"height"`
	SizeBytes int64  `json:"size_bytes"`
	Format    string `json:"format"`
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRowContext(ctx, createPhoto,
		arg.AlbumID,
		arg.Filename,
		arg.Width,
		arg.Height,
		arg.SizeBytes,
		arg.Format,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Filename,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Format,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrphanedPhotos = `-- name: DeleteOrphanedPhotos :many
DELETE FROM photos 
WHERE album_id NOT IN (SELECT id FROM albums)
RETURNING id, album_id, filename, format, created_at
`

type DeleteOrphanedPhotosRow struct {
	ID        int64        `json:"id"`
	AlbumID   int64        `json:"album_id"`
	Filename  string       `json:"filename"`
	Format    string       `json:"format"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) DeleteOrphanedPhotos(ctx context.Context) ([]DeleteOrphanedPhotosRow, error) {
	rows, err := q.db.QueryContext(ctx, deleteOrphanedPhotos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeleteOrphanedPhotosRow{}
	for rows.Next() {
		var i DeleteOrphanedPhotosRow
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.Filename,
			&i.Format,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePhoto = `-- name: DeletePhoto :exec
DELETE FROM photos WHERE id = ?
`

func (q *Queries) DeletePhoto(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePhoto, id)
	return err
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, album_id, filename, width, height, size_bytes, format, created_at FROM photos WHERE id = ?
`

func (q *Queries) GetPhoto(ctx context.Context, id int64) (Photo, error) {
	row := q.db.QueryRowContext(ctx, getPhoto, id)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Filename,
		&i.Width,
		&i.Height,
		&i.SizeBytes,
		&i.Format,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalStorageBytes = `-- name: GetTotalStorageBytes :one
SELECT COALESCE(SUM(size_bytes), 0) FROM photos
`

func (q *Queries) GetTotalStorageBytes(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalStorageBytes)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const listAllPhotosWithAlbum = `-- name: ListAllPhotosWithAlbum :many
SELECT 
    p.id, p.album_id, p.filename, p.width, p.height, p.size_bytes, p.format, p.created_at,
    a.title as album_title
FROM photos p
JOIN albums a ON p.album_id = a.id
ORDER BY p.created_at DESC
LIMIT ? OFFSET ?
`

type ListAllPhotosWithAlbumParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListAllPhotosWithAlbumRow struct {
	ID         int64        `json:"id"`
	AlbumID    int64        `json:"album_id"`
	Filename   string       `json:"filename"`
	Width      int64        `json:"width"`
	Height     int64        `json:"height"`
	SizeBytes  int64        `json:"size_bytes"`
	Format     string       `json:"format"`
	CreatedAt  sql.NullTime `json:"created_at"`
	AlbumTitle string       `json:"album_title"`
}

func (q *Queries) ListAllPhotosWithAlbum(ctx context.Context, arg ListAllPhotosWithAlbumParams) ([]ListAllPhotosWithAlbumRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllPhotosWithAlbum, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllPhotosWithAlbumRow{}
	for rows.Next() {
		var i ListAllPhotosWithAlbumRow
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.Filename,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.Format,
			&i.CreatedAt,
			&i.AlbumTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosByAlbum = `-- name: ListPhotosByAlbum :many
SELECT id, album_id, filename, width, height, size_bytes, format, created_at FROM photos WHERE album_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListPhotosByAlbumParams struct {
	AlbumID int64 `json:"album_id"`
	Limit   int64 `json:"limit"`
	Offset  int64 `json:"offset"`
}

func (q *Queries) ListPhotosByAlbum(ctx context.Context, arg ListPhotosByAlbumParams) ([]Photo, error) {
	rows, err := q.db.QueryContext(ctx, listPhotosByAlbum, arg.AlbumID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Photo{}
	for rows.Next() {
		var i Photo
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.Filename,
			&i.Width,
			&i.Height,
			&i.SizeBytes,
			&i.Format,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
