// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processing_queue.sql

package sqlc

import (
	"context"
	"database/sql"
)

const clearFailedJobs = `-- name: ClearFailedJobs :exec
DELETE FROM processing_queue
WHERE album_id = ? AND status = 'failed'
`

func (q *Queries) ClearFailedJobs(ctx context.Context, albumID int64) error {
	_, err := q.db.ExecContext(ctx, clearFailedJobs, albumID)
	return err
}

const countActiveJobs = `-- name: CountActiveJobs :one
SELECT COUNT(*) FROM processing_queue 
WHERE album_id = ? AND status IN ('pending', 'processing')
`

func (q *Queries) CountActiveJobs(ctx context.Context, albumID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveJobs, albumID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM processing_queue
WHERE id = ?
`

func (q *Queries) DeleteJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO processing_queue (
    album_id, original_filename, temp_filepath, status
) VALUES (
    ?, ?, ?, 'pending'
)
RETURNING id, album_id, original_filename, temp_filepath, status, error_message, created_at, updated_at
`

type EnqueueJobParams struct {
	AlbumID          int64  `json:"album_id"`
	OriginalFilename string `json:"original_filename"`
	TempFilepath     string `json:"temp_filepath"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (ProcessingQueue, error) {
	row := q.db.QueryRowContext(ctx, enqueueJob, arg.AlbumID, arg.OriginalFilename, arg.TempFilepath)
	var i ProcessingQueue
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.OriginalFilename,
		&i.TempFilepath,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextPendingJob = `-- name: GetNextPendingJob :one
UPDATE processing_queue
SET status = 'processing', updated_at = CURRENT_TIMESTAMP
WHERE id = (
  SELECT id FROM processing_queue
  WHERE status = 'pending'
  ORDER BY created_at ASC
  LIMIT 1
)
RETURNING id, album_id, original_filename, temp_filepath, status, error_message, created_at, updated_at
`

func (q *Queries) GetNextPendingJob(ctx context.Context) (ProcessingQueue, error) {
	row := q.db.QueryRowContext(ctx, getNextPendingJob)
	var i ProcessingQueue
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.OriginalFilename,
		&i.TempFilepath,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQueueStatus = `-- name: GetQueueStatus :one
SELECT 
    SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) AS pending_count,
    SUM(CASE WHEN status = 'processing' THEN 1 ELSE 0 END) AS processing_count,
    SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END) AS failed_count,
    SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) AS completed_count 
FROM processing_queue
WHERE album_id = ?
`

type GetQueueStatusRow struct {
	PendingCount    sql.NullFloat64 `json:"pending_count"`
	ProcessingCount sql.NullFloat64 `json:"processing_count"`
	FailedCount     sql.NullFloat64 `json:"failed_count"`
	CompletedCount  sql.NullFloat64 `json:"completed_count"`
}

func (q *Queries) GetQueueStatus(ctx context.Context, albumID int64) (GetQueueStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getQueueStatus, albumID)
	var i GetQueueStatusRow
	err := row.Scan(
		&i.PendingCount,
		&i.ProcessingCount,
		&i.FailedCount,
		&i.CompletedCount,
	)
	return i, err
}

const listFailedJobs = `-- name: ListFailedJobs :many
SELECT id, album_id, original_filename, temp_filepath, status, error_message, created_at, updated_at FROM processing_queue
WHERE album_id = ? AND status = 'failed'
ORDER BY created_at ASC
`

func (q *Queries) ListFailedJobs(ctx context.Context, albumID int64) ([]ProcessingQueue, error) {
	rows, err := q.db.QueryContext(ctx, listFailedJobs, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcessingQueue{}
	for rows.Next() {
		var i ProcessingQueue
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.OriginalFilename,
			&i.TempFilepath,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE processing_queue
SET status = ?, error_message = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateJobStatusParams struct {
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus, arg.Status, arg.ErrorMessage, arg.ID)
	return err
}
