// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	ClearAlbumCoverIfPhoto(ctx context.Context, coverPhotoID sql.NullInt64) error
	CountActivityByTypeSince(ctx context.Context, createdAt sql.NullTime) ([]CountActivityByTypeSinceRow, error)
	CountAlbumViewsSince(ctx context.Context, createdAt sql.NullTime) (int64, error)
	CountAlbums(ctx context.Context) (int64, error)
	CountPhotoViewsSince(ctx context.Context, createdAt sql.NullTime) (int64, error)
	CountPhotos(ctx context.Context) (int64, error)
	CountShareLinks(ctx context.Context) (int64, error)
	CountShareViewsSince(ctx context.Context, createdAt sql.NullTime) (int64, error)
	CountUniqueShareLinkViews(ctx context.Context, shareLinkID int64) (int64, error)
	CountUploadsSince(ctx context.Context, createdAt sql.NullTime) (int64, error)
	CreateActivityEvent(ctx context.Context, arg CreateActivityEventParams) error
	CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error)
	CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error)
	DeleteAlbum(ctx context.Context, id int64) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteExpiredShareLinks(ctx context.Context) ([]DeleteExpiredShareLinksRow, error)
	DeleteOldActivityEvents(ctx context.Context, createdAt sql.NullTime) error
	DeleteOrphanedPhotos(ctx context.Context) ([]DeleteOrphanedPhotosRow, error)
	DeletePhoto(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, id string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	GetAlbum(ctx context.Context, id int64) (Album, error)
	GetAlbumWithPhotoCount(ctx context.Context, id int64) (GetAlbumWithPhotoCountRow, error)
	GetPhoto(ctx context.Context, id int64) (Photo, error)
	GetPhotosForAlbum(ctx context.Context, albumID int64) ([]Photo, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetShareLink(ctx context.Context, id int64) (ShareLink, error)
	GetShareLinkByToken(ctx context.Context, token string) (ShareLink, error)
	GetTotalStorageBytes(ctx context.Context) (interface{}, error)
	IncrementShareLinkView(ctx context.Context, arg IncrementShareLinkViewParams) error
	ListActiveShareLinks(ctx context.Context, arg ListActiveShareLinksParams) ([]ShareLink, error)
	ListAlbums(ctx context.Context, arg ListAlbumsParams) ([]Album, error)
	ListAlbumsWithPhotoCount(ctx context.Context, arg ListAlbumsWithPhotoCountParams) ([]ListAlbumsWithPhotoCountRow, error)
	ListAllPhotosWithAlbum(ctx context.Context, arg ListAllPhotosWithAlbumParams) ([]ListAllPhotosWithAlbumRow, error)
	ListPhotosByAlbum(ctx context.Context, arg ListPhotosByAlbumParams) ([]Photo, error)
	ListRecentActivity(ctx context.Context, arg ListRecentActivityParams) ([]ActivityEvent, error)
	ListShareLinks(ctx context.Context, arg ListShareLinksParams) ([]ShareLink, error)
	ListShareLinksWithDetails(ctx context.Context, arg ListShareLinksWithDetailsParams) ([]ListShareLinksWithDetailsRow, error)
	RevokeShareLink(ctx context.Context, id int64) error
	SetAlbumCover(ctx context.Context, arg SetAlbumCoverParams) error
	UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) error
}

var _ Querier = (*Queries)(nil)
