// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: share_links.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createShareLink = `-- name: CreateShareLink :one
INSERT INTO share_links (token, target_type, target_id, max_views, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, token, target_type, target_id, max_views, expires_at, created_at, revoked_at
`

type CreateShareLinkParams struct {
	Token      string        `json:"token"`
	TargetType string        `json:"target_type"`
	TargetID   int64         `json:"target_id"`
	MaxViews   sql.NullInt64 `json:"max_views"`
	ExpiresAt  sql.NullTime  `json:"expires_at"`
}

func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRowContext(ctx, createShareLink,
		arg.Token,
		arg.TargetType,
		arg.TargetID,
		arg.MaxViews,
		arg.ExpiresAt,
	)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.TargetType,
		&i.TargetID,
		&i.MaxViews,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getShareLinkByToken = `-- name: GetShareLinkByToken :one
SELECT id, token, target_type, target_id, max_views, expires_at, created_at, revoked_at FROM share_links WHERE token = ?
`

func (q *Queries) GetShareLinkByToken(ctx context.Context, token string) (ShareLink, error) {
	row := q.db.QueryRowContext(ctx, getShareLinkByToken, token)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.TargetType,
		&i.TargetID,
		&i.MaxViews,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const incrementShareLinkView = `-- name: IncrementShareLinkView :exec
INSERT INTO share_link_views (share_link_id, viewer_hash) VALUES (?, ?)
`

type IncrementShareLinkViewParams struct {
	ShareLinkID int64  `json:"share_link_id"`
	ViewerHash  string `json:"viewer_hash"`
}

func (q *Queries) IncrementShareLinkView(ctx context.Context, arg IncrementShareLinkViewParams) error {
	_, err := q.db.ExecContext(ctx, incrementShareLinkView, arg.ShareLinkID, arg.ViewerHash)
	return err
}
